### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by sivajyothi1** [danielhomola/3D_UNet#1]
Hello Daniel,
I'm using python 3.6.7 version in ubuntu 18.04.
While using data_exploration.ipynb in the notebooks, i'm getting an error like this: 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3f1395848f0e> in <module>
     13 import matplotlib.pyplot as plt
     14 import sys
---> 15 from src.data_utils import Dataset
     16 
     17 # get TF logger - set it to info for more tracking process

ModuleNotFoundError: No module named 'src'

Can you please help me to resolve this issue??

**Comment by danielhomola** [comment]
You need to install the package with `pip install -e .`
